# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
